--LIBRARY ieee;
--USE ieee.std_logic_1164.all;
--
--ENTITY digital_X IS
--port ( 
--	ENTRADA1, ENTRADA2 : in std_logic_vector(3 downto 0);
--	SELECAO: in std_logic;
--	SAIDA : out std_logic_vector(3 downto 0)
--);
--END digital_X ;
--
--ARCHITECTURE digital_X_arch OF digital_X IS
--
--component mux2x1 IS
--port ( 
--	E1, E2, SEL: in std_logic;
--	S: out std_logic
--);
--END component;
--
--BEGIN
--	mux1 : mux2x1 port map(
--		E1 => ENTRADA1(0),
--		E2 => ENTRADA2(0),
--		SEL => SELECAO,
--		S => SAIDA(0)
--	);
--	mux2 : mux2x1 port map(
--		E1 => ENTRADA1(1),
--		E2 => ENTRADA2(1),
--		SEL => SELECAO,
--		S => SAIDA(1)
--	);
--	mux3 : mux2x1 port map(
--		E1 => ENTRADA1(2),
--		E2 => ENTRADA2(2),
--		SEL => SELECAO,
--		S => SAIDA(2)
--	);
--	mux4 : mux2x1 port map(
--		E1 => ENTRADA1(3),
--		E2 => ENTRADA2(3),
--		SEL => SELECAO,
--		S => SAIDA(3)
--	);
--END digital_X_arch ;